<?php
class Assets extends Wire implements Module
{
    protected $content_type = array(
        '.css'      => 'text/css',
        '.gif'      => 'image/gif',
        '.ico'      => 'image/x-icon',
        '.jpe'      => 'image/jpeg',
        '.jpeg'     => 'image/jpeg',
        '.jpg'      => 'image/jpeg',
        '.png'      => 'image/png',
        '.js'       => 'text/javascript',
        '.woff'     => 'application/font-woff',
    );
    
    // http://reference.sitepoint.com/html/mime-types-full
    // http://hul.harvard.edu/ois/systems/wax/wax-public-help/mimetypes.htm
    protected $supported_mimetype = array(
        'text/plain',
        'image/gif',
        'image/x-icon',
        'image/jpeg',
        'image/png',
        'text/html',
        'text/javascript',
        'application/x-javascript',
        'application/javascript',
        'application/ecmascript',
        'text/javascript',
        'text/ecmascript',
        'application/font-woff',
    );
    
    protected $exceptions = array(
        '/wire/modules/Jquery/JqueryTableSorter/JqueryTableSorter.js'
    );
    
    /**
	 * getModuleInfo is a module required by all modules to tell ProcessWire about them
	 *
	 * @return array
	 *
	 */
    public static function getModuleInfo() 
    {
        return array(
            'title' => 'Asset management, when you move your index.php to some where else', 
            'version' => 100, 
            'summary' => '',
            'author' => 'Hari KT',
            'href' => 'http://harikt.com/',
            'singular' => true, 
            'autoload' => true, 
        );
    }
    
    public function init()
    {
        $this->addHookBefore('ProcessPageView::pageNotFound', $this, 'displayAsset');
    }

    /**
     * 
     * If the supported type of file exists get the file and show it.
     * 
     * mimetype of css, js is text/plain
     * 
     * Even if someone change the .php file to .css or something, 
     * 
     * we don't need to serve
     * 
     * @param HookEvent $event
     * 
     * @return void
     * 
     */
    public function displayAsset($event)
    {
        $file = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
        $cachepath = $_SERVER['DOCUMENT_ROOT'] . $file;
        $realpath =  dirname(dirname(dirname(__DIR__))) . $file;
        $extension = '.' . pathinfo(parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH), PATHINFO_EXTENSION);
        /**
         * Mime detection becomes a hell, depending on PHP versions
         */
        $finfo = new finfo(FILEINFO_MIME_TYPE);
        $mimetype = $finfo->buffer($realpath);
        if ((array_key_exists($extension, $this->content_type) 
            && in_array($mimetype, $this->supported_mimetype)) 
            || in_array($file, $this->exceptions)
        ) {            
            if (file_exists($realpath)) {
                // make sure we have a dir for it
                $dir = dirname($cachepath);
                if (! is_dir($dir)) {
                    @mkdir($dir, 0755, true);
                }
                if (symlink($realpath, $cachepath)) {
                    // @copy($realpath, $cachepath);
                    header("Content-type: {$this->content_type[$extension]}");
                    echo file_get_contents($realpath);
                    exit;
                } else {
                    // failed
                    // @todo if in debug mode show the error that not able to create symbolic link
                }
            }
        }        
        return;
    }
}
